# Generated by Django 3.2.5 on 2024-02-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
